<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProfileSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('profiles')->insert([
            [
                'first_name' => 'John Paul',
                'last_name' => 'Linogao',
                'middle_initial' => 'C',
                'suffix' => null,
                'age' => 20,
                'address' => 'Magallanes, Agusan del Norte',
                'school_email' => 'john.linogao@urios.edu.ph',
                'sex' => 'male',
                'phone_number' => '09101631245',
                'admission_date' => now(),
                'marital_status' => 'single',
                'religion' => 'catholic',
                'photo_path' => null,
                'emer_full_name' => 'Rose Linogao',
                'relationship' => 'Mother',
                'emer_contact_no' => '09101812345',
                'date_of_birth' => '2003-03-25',
                'user_id' => 1,
                'program_department_id' => null,
                'yearlevel_id' => 3,
                'parent_info_id' => 1,
                'department_id' => null,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],

            [
                'first_name' => 'Michael Danville',
                'last_name' => 'Enciso',
                'middle_initial' => 'C',
                'suffix' => null,
                'age' => 20,
                'address' => 'Magallanes, Agusan del Norte',
                'school_email' => 'michael.enciso@urios.edu.ph',
                'sex' => 'male',
                'phone_number' => '09101631245',
                'admission_date' => now(),
                'marital_status' => 'single',
                'religion' => 'catholic',
                'photo_path' => null,
                'emer_full_name' => 'Rose Linogao',
                'relationship' => 'Mother',
                'emer_contact_no' => '09101812345',
                'date_of_birth' => '2003-03-25',
                'user_id' => 2,
                'program_department_id' => null,
                'yearlevel_id' => 3,
                'parent_info_id' => 1,
                'department_id' => null,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],

            [
                'first_name' => 'Nazir',
                'last_name' => 'Buenavidez',
                'middle_initial' => 'A',
                'suffix' => null,
                'age' => 20,
                'address' => 'Magallanes, Agusan del Norte',
                'school_email' => 'nazir.buenavidez@urios.edu.ph',
                'sex' => 'male',
                'phone_number' => '09101631245',
                'admission_date' => now(),
                'marital_status' => 'single',
                'religion' => 'catholic',
                'photo_path' => null,
                'emer_full_name' => 'Rose Linogao',
                'relationship' => 'Mother',
                'emer_contact_no' => '09101812345',
                'date_of_birth' => '2003-03-25',
                'user_id' => 3,
                'program_department_id' => null,
                'yearlevel_id' => 3,
                'parent_info_id' => 1,
                'department_id' => null,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],

            [
                'first_name' => 'Khim',
                'last_name' => 'Lucintes',
                'middle_initial' => 'B',
                'suffix' => null,
                'age' => 20,
                'address' => 'Magallanes, Agusan del Norte',
                'school_email' => 'khim.lucintes@urios.edu.ph',
                'sex' => 'male',
                'phone_number' => '09101631245',
                'admission_date' => now(),
                'marital_status' => 'single',
                'religion' => 'catholic',
                'photo_path' => null,
                'emer_full_name' => 'Rose Linogao',
                'relationship' => 'Mother',
                'emer_contact_no' => '09101812345',
                'date_of_birth' => '2003-03-25',
                'user_id' => 4,
                'program_department_id' => null,
                'yearlevel_id' => 3,
                'parent_info_id' => 1,
                'department_id' => null,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],

            [
                'first_name' => 'Sofia',
                'last_name' => 'Reyes',
                'middle_initial' => 'M',
                'suffix' => null,
                'age' => 22,
                'address' => 'Cagayan de Oro City',
                'school_email' => 'sofia.reyes@urios.edu.ph',
                'sex' => 'female',
                'phone_number' => '09107894567',
                'admission_date' => now(),
                'marital_status' => 'single',
                'religion' => 'christian',
                'photo_path' => null,
                'emer_full_name' => 'Maria Reyes',
                'relationship' => 'Mother',
                'emer_contact_no' => '09107894568',
                'date_of_birth' => '2001-05-15',
                'user_id' => 5,
                'program_department_id' => null,
                'yearlevel_id' => 4,
                'parent_info_id' => 5,
                'department_id' => null,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],

            [
                'first_name' => 'Jasper',
                'last_name' => 'Castro',
                'middle_initial' => 'R',
                'suffix' => null,
                'age' => 21,
                'address' => 'Butuan City',
                'school_email' => 'jasper.castro@urios.edu.ph',
                'sex' => 'male',
                'phone_number' => '09234567890',
                'admission_date' => now(),
                'marital_status' => 'single',
                'religion' => 'christian',
                'photo_path' => null,
                'emer_full_name' => 'Luis Castro',
                'relationship' => 'Father',
                'emer_contact_no' => '09234567891',
                'date_of_birth' => '2002-11-10',
                'user_id' => 6,
                'program_department_id' => null,
                'yearlevel_id' => 4,
                'parent_info_id' => 2,
                'department_id' => null,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],

            [
                'first_name' => 'Diana',
                'last_name' => 'Salazar',
                'middle_initial' => 'L',
                'suffix' => null,
                'age' => 23,
                'address' => 'Surigao City',
                'school_email' => 'diana.salazar@urios.edu.ph',
                'sex' => 'female',
                'phone_number' => '09323456789',
                'admission_date' => now(),
                'marital_status' => 'single',
                'religion' => 'christian',
                'photo_path' => null,
                'emer_full_name' => 'Clara Salazar',
                'relationship' => 'Mother',
                'emer_contact_no' => '09323456790',
                'date_of_birth' => '2000-02-18',
                'user_id' => 7,
                'program_department_id' => null,
                'yearlevel_id' => 2,
                'parent_info_id' => 6,
                'department_id' => null,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],

            [
                'first_name' => 'Marco',
                'last_name' => 'Villanueva',
                'middle_initial' => 'D',
                'suffix' => null,
                'age' => 24,
                'address' => 'Tandag City',
                'school_email' => 'marco.villanueva@urios.edu.ph',
                'sex' => 'male',
                'phone_number' => '09456789012',
                'admission_date' => now(),
                'marital_status' => 'single',
                'religion' => 'christian',
                'photo_path' => null,
                'emer_full_name' => 'Carlos Villanueva',
                'relationship' => 'Father',
                'emer_contact_no' => '09456789013',
                'date_of_birth' => '1999-09-25',
                'user_id' => 8,
                'program_department_id' => null,
                'yearlevel_id' => 5,
                'parent_info_id' => 3,
                'department_id' => null,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],

            [
                'first_name' => 'Elena',
                'last_name' => 'Gonzales',
                'middle_initial' => 'T',
                'suffix' => null,
                'age' => 22,
                'address' => 'Cebu City',
                'school_email' => 'elena.gonzales@urios.edu.ph',
                'sex' => 'female',
                'phone_number' => '09512345678',
                'admission_date' => now(),
                'marital_status' => 'single',
                'religion' => 'christian',
                'photo_path' => null,
                'emer_full_name' => 'Jose Gonzales',
                'relationship' => 'Brother',
                'emer_contact_no' => '09512345679',
                'date_of_birth' => '2001-08-11',
                'user_id' => 9,
                'program_department_id' => null,
                'yearlevel_id' => 4,
                'parent_info_id' => 4,
                'department_id' => null,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
        ]);
    }
}